### ISSUE TITLE
Addition of test scenarios in a pull request should have its rule reported as changed

### ISSUE THREAD

**Issue by ggbecker** [mildas/content-test-filtering#13]
This PR https://github.com/ComplianceAsCode/content/pull/7313 adds a new templated rule and test scenarios. It's a good idea to report the rule id in the JSON output format in this case so the rule is tested by the SSGTS GH integration.

**Comment by ggbecker** [comment]
Also, if a template section is added or modified we should consider reporting the rule id as well.

**Comment by jan-cerny** [comment]
I agree, when a new rule or new tests are added, I need to run the tests during the review, so having them detected would be amazing!

**Comment by ggbecker** [comment]
Another thing I noticed is that rule ids are reported even when the rule doesn't have any test scenarios. Maybe we should avoid reporting them as the SSGTS shows an error when a rule is tested and there are no test scenarios.

I also saw sometimes duplicates in the output, for example the same rule reported twice in the JSON output. I think we can use some sort of unique list (e.g set)

**Comment by mildas** [comment]
CTF doesn't have analyzers for `rule.yml` and test scenarios yet. Now, it ignores those files. I will start working on it as soon as possible.

@ggbecker Good idea about missing test scenarios. On the other hand, SSGTS error that there are no test scenarios might be useful warning for reviewer. When a rule without test scenarios is added/modified, we should request creating test scenarios.
Do you have a PR where same rule got reported twice?

**Comment by ggbecker** [comment]
> CTF doesn't have analyzers for `rule.yml` and test scenarios yet. Now, it ignores those files. I will start working on it as soon as possible.
> 
> @ggbecker Good idea about missing test scenarios. On the other hand, SSGTS error that there are no test scenarios might be useful warning for reviewer. When a rule without test scenarios is added/modified, we should request creating test scenarios.
> Do you have a PR where same rule got reported twice?

$ python3 content_test_filtering.py pr --rule --output json 6910
`
{"rules": ["audit_rules_privileged_commands_kmod", "audit_rules_privileged_commands_kmod", "audit_rules_sudoers", "audit_rules_sudoers", "audit_rules_sudoers", "audit_rules_sudoers_d", "audit_rules_sudoers_d", "audit_rules_sudoers_d", "auditd_overflow_action", "auditd_overflow_action", "auditd_overflow_action"], "product": "rhel8", "bash": "True", "ansible": "True"
`

**Comment by ggbecker** [comment]
Fixed by #16 #17 #18
