### ISSUE TITLE
Use collections.defaultdict to simplify code

### ISSUE THREAD

**Issue by matejak** [mildas/content-test-filtering#3]
The code in DiffLogging.py often looks like

```
            if rule in self.rules:
                self.rules[rule].add(msg)
            else:
                self.rules[rule] = {msg}
```

You can use the defaultdict type to save yourself some boring code:

https://docs.python.org/3.8/library/collections.html#collections.defaultdict

**Comment by mildas** [comment]
The problem is the attribute is in the format: 
```
{"product1": 
    set("rule1", "rule2"),
"product2":
    set("rule3", "rule4")}
```
If I would use `defaultdict`, then I still need to initialize `set` for each new product I want to add to the variable.

**Comment by mildas** [comment]
Thank you for the recommendation. The code looks better now, see 59cc5a31
