### ISSUE TITLE
Path to test_suite.py needs dir prefix

### ISSUE THREAD

**Issue by yuumasato** [mildas/content-test-filtering#4]
In https://github.com/ComplianceAsCode/content/pull/5609, the `content-test-filtering` instructed to run:
* `build_product fedora`
* `test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate ansible --datastream build/ssg-fedora-ds.xml audit_rules_immutable`

The second command should probably be:
* `tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate ansible --datastream build/ssg-fedora-ds.xml audit_rules_immutable`

Note: I don't know how `--remediate ansible` is actually working. The option I see in `test_suite.py` is `--remediate-using`.

**Comment by mildas** [comment]
Thank you for the report. Fixed in 618b270
