### ISSUE TITLE
[RFE] Edit existent comment instead of always adding a new one

### ISSUE THREAD

**Issue by ggbecker** [mildas/content-test-filtering#6]
Identify if there is already a comment related to content-test-filtering and edit instead of always adding a new one

**Comment by mildas** [comment]
Thank you for the issue. I've updated the `comment_pr.py` script https://github.com/mildas/content-test-filtering/commit/c1257bb166c028518cf2ac8a370a30adb84ea35d and it should edit already existing comments now.

@ggbecker Please, can you verify that it works as expected?

**Comment by ggbecker** [comment]
It seems to work. Thanks.
